module Protocol exposing
    ( Auth_Common_AuthChallengeReason(..)
    , Auth_Common_AuthCode
    , Auth_Common_Error(..)
    , Auth_Common_MethodId
    , Auth_Common_State
    , Auth_Common_ToBackend(..)
    , Auth_Common_ToFrontend(..)
    , Auth_Common_UserInfo
    , Logger_LogEntry
    , Logger_LogLevel(..)
    , OAuth_AuthorizationCode_AuthenticationError
    , OAuth_AuthorizationCode_AuthorizationError
    , OAuth_ErrorCode(..)
    , Email
    , EmailPasswordAuthToBackend(..)
    , Preferences
    , UserFrontend
    , WorldCoordinates(..)
    , WireToBackend(..)
    , WireToFrontend(..)
    )

{-| Auto-generated wire protocol types for ToBackend / ToFrontend.

Single-module freeze of the app wire surface for Wire3-compatible clients.
Generated by wire-extractor. Do not edit by hand.

Roots:
  - ToBackend  ← Types.ToBackend
  - ToFrontend ← Types.ToFrontend
-}

import Url exposing (Url)
import Length
import Point3d

type Auth_Common_AuthChallengeReason
    = AuthSessionMissing
    | AuthSessionInvalid
    | AuthSessionExpired
    | AuthSessionLoggedOut

type alias Auth_Common_AuthCode =
    String

type Auth_Common_Error
    = ErrStateMismatch
    | ErrAuthorization OAuth_AuthorizationCode_AuthorizationError
    | ErrAuthentication OAuth_AuthorizationCode_AuthenticationError
    | ErrHTTPGetAccessToken
    | ErrHTTPGetUserInfo
    | ErrAuthString String

type alias Auth_Common_MethodId =
    String

type alias Auth_Common_State =
    String

type Auth_Common_ToBackend
    = AuthSigninInitiated { methodId : Auth_Common_MethodId, baseUrl : Url, username : Maybe String }
    | AuthCallbackReceived Auth_Common_MethodId Url Auth_Common_AuthCode Auth_Common_State
    | AuthRenewSessionRequested
    | AuthLogoutRequested

type Auth_Common_ToFrontend
    = AuthInitiateSignin Url
    | AuthError Auth_Common_Error
    | AuthSessionChallenge Auth_Common_AuthChallengeReason

type alias Auth_Common_UserInfo =
    { email : String, name : Maybe String, username : Maybe String, picture : Maybe String }

type alias Logger_LogEntry =
    { index : Int, timestamp : Int, level : Logger_LogLevel, message : String }

type Logger_LogLevel
    = Debug
    | Info
    | Warn
    | Error

type alias OAuth_AuthorizationCode_AuthenticationError =
    { error : OAuth_ErrorCode, errorDescription : Maybe String, errorUri : Maybe String }

type alias OAuth_AuthorizationCode_AuthorizationError =
    { error : OAuth_ErrorCode, errorDescription : Maybe String, errorUri : Maybe String, state : Maybe String }

type OAuth_ErrorCode
    = InvalidRequest
    | UnauthorizedClient
    | AccessDenied
    | UnsupportedResponseType
    | InvalidScope
    | ServerError
    | TemporarilyUnavailable
    | Custom String

type alias Email =
    String

type EmailPasswordAuthToBackend
    = EmailPasswordLoginToBackend String String
    | EmailPasswordSignupToBackend String String (Maybe String)

type alias Preferences =
    { darkMode : Bool }

type alias UserFrontend =
    { email : Email, isSysAdmin : Bool, role : String, preferences : Preferences }

type WorldCoordinates
    = WorldCoordinates

type WireToBackend
    = A String
    | Admin_ClearLogs
    | Admin_FetchLogs String
    | Admin_FetchRemoteModel String
    | AuthToBackend Auth_Common_ToBackend
    | EmailPasswordAuthToBackend EmailPasswordAuthToBackend
    | GetUserToBackend
    | LoggedOut
    | NoOpToBackend
    | SetDarkModePreference Bool
    | UploadMesh (Point3d.Point3d Length.Meters WorldCoordinates)

type WireToFrontend
    = A0 String
    | Admin_Logs_ToFrontend (List Logger_LogEntry)
    | AuthSuccess Auth_Common_UserInfo
    | AuthToFrontend Auth_Common_ToFrontend
    | MeshPointEcho (Point3d.Point3d Length.Meters WorldCoordinates)
    | NoOpToFrontend
    | PermissionDenied WireToBackend
    | UserDataToFrontend UserFrontend
    | UserInfoMsg (Maybe Auth_Common_UserInfo)
