module ProtocolWireProof exposing (suite)

{-| AUTO-GENERATED by wire-extractor. Do not edit.

Property + exhaustive Wire3 identity: Protocol ↔ Types for ToBackend/ToFrontend.
-}

import Expect exposing (Expectation)
import Lamdera.Wire3 as Wire3
import Protocol
import Fuzz
import Test exposing (Test, describe, fuzz, test)
import Types
import Url exposing (Url)
import Length
import Point3d

exampleUrl : Url
exampleUrl =
    case Url.fromString "https://example.com/callback" of
        Just u ->
            u

        Nothing ->
            { protocol = Url.Https
            , host = "example.com"
            , port_ = Nothing
            , path = "/callback"
            , query = Nothing
            , fragment = Nothing
            }


allToBackend : List ( String, Protocol.WireToBackend )
allToBackend =
    [ ( "A", Protocol.A ("") )
    , ( "Admin_ClearLogs", Protocol.Admin_ClearLogs )
    , ( "Admin_FetchLogs", Protocol.Admin_FetchLogs ("") )
    , ( "Admin_FetchRemoteModel", Protocol.Admin_FetchRemoteModel ("") )
    , ( "AuthToBackend", Protocol.AuthToBackend (Protocol.AuthRenewSessionRequested) )
    , ( "EmailPasswordAuthToBackend", Protocol.EmailPasswordAuthToBackend (Protocol.EmailPasswordLoginToBackend ("") ("")) )
    , ( "GetUserToBackend", Protocol.GetUserToBackend )
    , ( "LoggedOut", Protocol.LoggedOut )
    , ( "NoOpToBackend", Protocol.NoOpToBackend )
    , ( "SetDarkModePreference", Protocol.SetDarkModePreference (False) )
    , ( "UploadMesh", Protocol.UploadMesh (Point3d.origin) )
    ]

allToFrontend : List ( String, Protocol.WireToFrontend )
allToFrontend =
    [ ( "A0", Protocol.A0 ("") )
    , ( "Admin_Logs_ToFrontend", Protocol.Admin_Logs_ToFrontend ([]) )
    , ( "AuthSuccess", Protocol.AuthSuccess ({ email = "", name = Nothing, username = Nothing, picture = Nothing }) )
    , ( "AuthToFrontend", Protocol.AuthToFrontend (Protocol.AuthInitiateSignin (exampleUrl)) )
    , ( "MeshPointEcho", Protocol.MeshPointEcho (Point3d.origin) )
    , ( "NoOpToFrontend", Protocol.NoOpToFrontend )
    , ( "PermissionDenied", Protocol.PermissionDenied (Protocol.Admin_ClearLogs) )
    , ( "UserDataToFrontend", Protocol.UserDataToFrontend ({ email = "", isSysAdmin = False, role = "", preferences = { darkMode = False } }) )
    , ( "UserInfoMsg", Protocol.UserInfoMsg (Nothing) )
    ]

roundTripToBackend : Protocol.WireToBackend -> Expectation
roundTripToBackend protocolVal =
    let
        protocolBytes =
            Wire3.bytesEncode (Protocol.w3_encode_WireToBackend protocolVal)

        protocolList =
            Wire3.intListFromBytes protocolBytes
    in
    case Wire3.bytesDecode Types.w3_decode_ToBackend protocolBytes of
        Nothing ->
            Expect.fail
                ("App failed to decode protocol ToBackend bytes: "
                    ++ Debug.toString protocolList
                )

        Just appVal ->
            let
                appBytes =
                    Wire3.bytesEncode (Types.w3_encode_ToBackend appVal)

                appList =
                    Wire3.intListFromBytes appBytes
            in
            if protocolList /= appList then
                Expect.fail
                    ("ToBackend Wire3 byte mismatch\n  protocol: "
                        ++ Debug.toString protocolList
                        ++ "\n  app:      "
                        ++ Debug.toString appList
                    )

            else
                case Wire3.bytesDecode Protocol.w3_decode_WireToBackend appBytes of
                    Nothing ->
                        Expect.fail "Protocol failed to decode app ToBackend bytes"

                    Just protocolVal2 ->
                        let
                            again =
                                Wire3.intListFromBytes
                                    (Wire3.bytesEncode (Protocol.w3_encode_WireToBackend protocolVal2))
                        in
                        Expect.equal protocolList again


roundTripToFrontend : Protocol.WireToFrontend -> Expectation
roundTripToFrontend protocolVal =
    let
        protocolBytes =
            Wire3.bytesEncode (Protocol.w3_encode_WireToFrontend protocolVal)

        protocolList =
            Wire3.intListFromBytes protocolBytes
    in
    case Wire3.bytesDecode Types.w3_decode_ToFrontend protocolBytes of
        Nothing ->
            Expect.fail
                ("App failed to decode protocol ToFrontend bytes: "
                    ++ Debug.toString protocolList
                )

        Just appVal ->
            let
                appBytes =
                    Wire3.bytesEncode (Types.w3_encode_ToFrontend appVal)

                appList =
                    Wire3.intListFromBytes appBytes
            in
            if protocolList /= appList then
                Expect.fail
                    ("ToFrontend Wire3 byte mismatch\n  protocol: "
                        ++ Debug.toString protocolList
                        ++ "\n  app:      "
                        ++ Debug.toString appList
                    )

            else
                case Wire3.bytesDecode Protocol.w3_decode_WireToFrontend appBytes of
                    Nothing ->
                        Expect.fail "Protocol failed to decode app ToFrontend bytes"

                    Just protocolVal2 ->
                        let
                            again =
                                Wire3.intListFromBytes
                                    (Wire3.bytesEncode (Protocol.w3_encode_WireToFrontend protocolVal2))
                        in
                        Expect.equal protocolList again


suite : Test
suite =
    describe "Wire protocol identity (Protocol ↔ Types)"
        [ describe "ToBackend every constructor (minimal samples)"
            (List.map
                (\( name, value ) ->
                    test ("ToBackend." ++ name) <|
                        \_ -> roundTripToBackend value
                )
                allToBackend
            )
        , describe "ToFrontend every constructor (minimal samples)"
            (List.map
                (\( name, value ) ->
                    test ("ToFrontend." ++ name) <|
                        \_ -> roundTripToFrontend value
                )
                allToFrontend
            )

        , describe "ToBackend property (fuzzable constructors)"
            [ fuzz (Fuzz.map Protocol.A (Fuzz.string)) "property ToBackend.A" roundTripToBackend
            , fuzz (Fuzz.constant Protocol.Admin_ClearLogs) "property ToBackend.Admin_ClearLogs" roundTripToBackend
            , fuzz (Fuzz.map Protocol.Admin_FetchLogs (Fuzz.string)) "property ToBackend.Admin_FetchLogs" roundTripToBackend
            , fuzz (Fuzz.map Protocol.Admin_FetchRemoteModel (Fuzz.string)) "property ToBackend.Admin_FetchRemoteModel" roundTripToBackend
            , fuzz (Fuzz.constant Protocol.GetUserToBackend) "property ToBackend.GetUserToBackend" roundTripToBackend
            , fuzz (Fuzz.constant Protocol.LoggedOut) "property ToBackend.LoggedOut" roundTripToBackend
            , fuzz (Fuzz.constant Protocol.NoOpToBackend) "property ToBackend.NoOpToBackend" roundTripToBackend
            , fuzz (Fuzz.map Protocol.SetDarkModePreference (Fuzz.bool)) "property ToBackend.SetDarkModePreference" roundTripToBackend
            ]
        , describe "ToFrontend property (fuzzable constructors)"
            [ fuzz (Fuzz.map Protocol.A0 (Fuzz.string)) "property ToFrontend.A0" roundTripToFrontend
            , fuzz (Fuzz.constant Protocol.NoOpToFrontend) "property ToFrontend.NoOpToFrontend" roundTripToFrontend
            ]
        ]
